---
- name: Converge
  hosts: all
  roles:
    - role: macinit
      vars:
        macinit_do_customize: true
        macinit_homebrew: []
        macinit_homebrew_cask: []
        macinit_uv_tools: []
