---
- name: Initialize Macbook
  hosts: all
    
  roles:
    - role: macinit
      vars: 
        do_customize: no
        homebrew_tap:
          - buo/cask-upgrade
          - fluxcd/tap
          - homebrew/bundle
          - homebrew/cask-fonts
          - homebrew/cask-versions
          - romkatv/powerlevel10k
          - warrensbox/tap

        homebrew:
          - Azure/kubelogin/kubelogin
          - age
          - ansible
          - ansible-lint
          - azcopy
          - azure-cli
          - base64
          - bat
          - bitwarden-cli
          - derailed/k9s/k9s
          - dos2unix
          - esolitos/ipa/sshpass
          - ffmpeg
          - fluxcd/tap/flux
          - fzf
          - git
          - gnupg
          - go
          - helm
          - htop
          - istioctl
          - jq
          - kind
          - kubectx
          - kubernetes-cli
          - kustomize
          - libpq
          - minikube
          - neofetch
          - pass
          - pipx
          - powerlevel10k
          - pre-commit
          - rclone
          - reattach-to-user-namespace
          - romkatv/powerlevel10k/powerlevel10k
          - rsync
          - sops
          - ssh-copy-id
          - stern
          # - terraform
          - terraform-docs
          - terraform-ls
          - tflint
          - tfsec
          - tmux
          - tree
          - vim
          - warrensbox/tap/tfswitch
          - watch
          - wget
          - youtube-dl
          - yq
          - zsh
          - zsh-completions

        homebrew_cask:
          - adoptopenjdk
          - alt-tab
          - anki
          - bitwarden
          - brave-browser
          - dbeaver-community
          - docker
          - drawio
          - dropbox
          - firefox
          - font-blex-mono-nerd-font
          - gitkraken
          - google-chrome
          - google-drive
          - handbrake
          - intellij-idea-ce
          - iterm2
          - itsycal
          - licecap
          - macpass
          - microsoft-auto-update
          - microsoft-edge
          - microsoft-office
          - microsoft-teams
          - monitorcontrol
          - multipass
          # - mysqlworkbench
          - postman
          - rectangle
          - spotify
          - sublime-text
          - telegram
          - the-unarchiver
          - tor-browser
          # - vagrant
          # - virtualbox
          # - virtualbox-extension-pack
          - visual-studio-code
          - vlc
          - whatsapp

        pip_packages:
          - az-account-switcher 
