---
do_customize: false

homebrew_tap:
  - Azure/kubelogin
  - aquasecurity/trivy
  - fluxcd/tap
  - warrensbox/tap

homebrew:
  - age
  - ansible
  - ansible-lint
  - azcopy
  - azure-cli
  - base64
  - bash
  - bat
  - bitwarden-cli
  - crane
  - curl
  - direnv
  - dos2unix
  - eza
  - fd
  - ffmpeg
  - fluxcd/tap/flux
  - fzf
  - gist
  - git
  - git-filter-repo
  - git-lfs
  - gitleaks
  - gnupg
  - go
  - helm
  - htop
  - httpie
  - istioctl
  - jenv
  - jq
  - just
  - kind
  - krew
  - kubeconform
  - kubectx
  - Azure/kubelogin/kubelogin
  - kubernetes-cli
  - kustomize
  - lazygit
  - libpq
  - powerlevel10k
  - pre-commit
  - rclone
  - ripgrep
  - rsync
  - sops
  - ssh-copy-id
  - sshpass
  - sshuttle
  - stern
  - syft
  - terraform-docs
  - terraform-ls
  - tflint
  - tmux
  - tree
  - aquasecurity/trivy/trivy
  - uv
  - vim
  - watch
  - wget
  - yq
  - yt-dlp
  - zoxide
  - zsh
  - zsh-completions
  - zsh-syntax-highlighting

homebrew_cask:
  - alt-tab
  - anki
  - antigravity
  - balenaetcher
  - betterdisplay
  - bitwarden
  - brave-browser
  - bruno
  - claude-code
  - codex
  - dbeaver-community
  - docker-desktop
  - drawio
  - dropbox
  - firefox
  - font-blex-mono-nerd-font
  - google-chrome
  - google-drive
  - intellij-idea
  - iterm2
  - itermai
  - itsycal
  - jetbrains-toolbox
  - macpass
  - microsoft-auto-update
  - microsoft-edge
  - microsoft-office
  - microsoft-teams
  - nordvpn
  - obsidian
  - orbstack
  - raycast
  - rectangle
  - slack
  - spotify
  - stats
  - telegram
  - temurin
  - temurin@17
  - temurin@21
  - warrensbox/tap/tfswitch
  - tor-browser
  - visual-studio-code
  - vlc
  - whatsapp

uv_tools:
  - az-account-switcher
