---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml

driver:
  name: default

platforms:
  - name: localhost

provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: /usr/bin/python3
      roles_path: ${MOLECULE_PROJECT_DIRECTORY}/roles
  inventory:
    hosts:
      all:
        hosts:
          localhost:
            ansible_connection: local

verifier:
  name: ansible

scenario:
  test_sequence:
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - verify
    - cleanup
    - destroy

lint: |
  yamllint .
  ansible-lint .
