---
- name: Converge
  hosts: all
  roles:
    - role: macinit
      vars:
        macinit_do_customize: false
        macinit_homebrew:
          - git
          - curl
          - jq
          - bat
          - uv
        macinit_homebrew_cask: []
        macinit_uv_tools:
          - az-account-switcher
