---
brew_prefix: "{{ (ansible_machine == 'arm64') | ternary('/opt/homebrew', '/usr/local') }}"
brew_bin_path: "{{ brew_prefix }}/bin"
homebrew_tap: []
homebrew: []
homebrew_cask: []
pip_packages: []
pip: no
pipx: yes
pipx_packages_bin_dir: ~/.local/bin
do_customize: yes
vim_colors_dir: ~/.vim/pack/colors
vim_plugins_dir: ~/.vim/pack/plugins
