---
galaxy_info:
  author: Mehdi Hassanpour
  description: Bootstrap macOS (Apple Silicon) with Homebrew packages, casks, and dotfiles
  license: MIT

  min_ansible_version: "2.14"

  platforms:
    - name: macOS
      versions:
        - all

  galaxy_tags:
    - macos
    - homebrew
    - dotfiles
    - devops

dependencies: []
