---
- name: Install Homebrew
  ansible.builtin.include_tasks: homebrew.yml
  tags: [brew]

- name: Install and upgrade packages
  ansible.builtin.include_tasks: packages.yml
  tags: [packages]

- name: Copy dotfiles and clone Git repos
  ansible.builtin.include_tasks: dotfiles.yml
  when: do_customize | bool
  tags: [dotfiles]

- name: Fix zsh completion permissions
  ansible.builtin.include_tasks: zsh.yml
  when: zsh_fix_compinit_permissions | bool
  tags: [zsh, dotfiles]

- name: Run cleanup
  ansible.builtin.include_tasks: cleanup.yml
  tags: [cleanup]
