---
- name: Configure passwordless sudo
  ansible.builtin.copy:
    content: "{{ ansible_facts['user_id'] }}  ALL = (ALL) NOPASSWD: ALL\n"
    dest: "/etc/sudoers.d/{{ ansible_facts['user_id'] }}"
    owner: root
    group: wheel
    mode: "0440"
    validate: /usr/sbin/visudo -cf %s
  become: true
  tags: [dotfiles, sudo]

- name: Check if oh-my-zsh is already installed
  ansible.builtin.stat:
    path: ~/.oh-my-zsh
  register: omz_dir
  check_mode: false
  tags: [dotfiles, omz]

- name: Install oh-my-zsh
  ansible.builtin.shell:
    cmd: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  environment:
    RUNZSH: "no"
    CHSH: "no"
  when: not omz_dir.stat.exists
  tags: [dotfiles, omz]

- name: Clone Vim plugins
  ansible.builtin.git:
    dest: "{{ vim_plugins_dir }}/start/{{ item.name }}"
    repo: "{{ item.url }}"
    clone: true
    update: true
    recursive: false
  loop: "{{ vim_plugins }}"
  become: false
  tags: [dotfiles, vim]

- name: Clone Vim color schemes
  ansible.builtin.git:
    dest: "{{ vim_colors_dir }}/start/{{ item.name }}"
    repo: "{{ item.url }}"
    clone: true
    update: true
    recursive: false
  loop: "{{ vim_color_schemes }}"
  become: false
  tags: [dotfiles, vim]

- name: Clone Gregory Pakosz's .tmux
  ansible.builtin.git:
    dest: "~/.tmux"
    repo: "{{ tmux_repo }}"
    clone: true
    update: true
    recursive: false
  become: false
  tags: [dotfiles, tmux]

- name: Clone zsh custom plugins
  ansible.builtin.git:
    dest: "{{ omz_plugins_dir }}/{{ item.name }}"
    repo: "{{ item.url }}"
    clone: true
    update: true
    recursive: false
  loop: "{{ zsh_plugins }}"
  become: false
  tags: [dotfiles, zsh]

- name: Copy dotfiles
  ansible.builtin.copy:
    src: dotfiles/
    dest: "~/"
    backup: true
    mode: "0640"
  tags: [dotfiles]

- name: Symlink .tmux.conf
  ansible.builtin.file:
    src: "~/.tmux/.tmux.conf"
    dest: "~/.tmux.conf"
    force: true
    state: link
  tags: [dotfiles, tmux]
