---
- name: pick the correct set of tasks based on OS family
  include_tasks: '{{ os_family }}'
  with_first_found:
    - '{{ ansible_os_family }}.yml'
    - not-supported.yml
  loop_control:
    loop_var: os_family
