---
- name: tapping homebrew repos
  homebrew_tap:
    name: "{{ homebrew_tap }}"
    state: present

- name: install brew packages
  block:
    - name: install brew packages
      homebrew:
        name: "{{ item.name | default(item) }}"
        state: present
        install_options: "{{ item.install_options | default() }}"
        update_homebrew: yes
      with_items: "{{ homebrew }}"
  rescue: 
    - name: print when failed
      debug: 
        msg: Some packages where not installed successfully!
  
- name: Update homebrew and upgrade all packages
  homebrew:
    update_homebrew: yes
    upgrade_all: yes
    upgrade_options: ignore-pinned

- name: install brew cask packages
  block:
    - name: install brew cask packages
      homebrew_cask:
        name: "{{ item.name | default(item) }}"
        state: present
        install_options: "{{ item.install_options | default() }}"
        update_homebrew: yes
      with_items: "{{ homebrew_cask }}"
  rescue: 
    - name: print when failed
      debug: 
        msg: Some packages where not installed successfully!

- name: upgrading all casks
  homebrew_cask:
    upgrade_all: true  
  register: upgrade
  until: upgrade is successful

- name: install pip packages.
  pip:
    name: "{{ pip_packages }}"
    state: present
    executable: "{{ pip.executable | default(omit) }}"
  when: pip

- name: Check if pipx is installed
  stat: 
    path: "{{ brew_bin_path }}/pipx"
  register: pipx_bin
  check_mode: no

- name: Install & Upgrade pip packages
  block:
    - name: check if pip packages already installed
      stat: 
        path: "{{ pipx_packages_bin_dir }}/{{ item }}"
      with_items: "{{ pip_packages }}"
      register: pipx_packages_bin
      check_mode: no

    - name: install pip packages using pipx
      command: "{{ brew_bin_path }}/pipx install {{ item.item }}"
      with_items: "{{ pipx_packages_bin.results }}"
      when: not item.stat.exists

    - name: upgrade pip packages installed using pipx
      command: "{{ brew_bin_path }}/pipx upgrade-all" 

  when: 
    - pipx
    - pipx_bin.stat.exists
